name: Code quality and Testing

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8.5, 3.9]
    steps:
      - name: Get code
        uses: actions/checkout@v2
      - name: Python setup  ${{ matrix.python-version }}
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.0
      - name: Install dependencies through poetry
        run: poetry install
      - name: Run tests and coverage
        run: poetry run pytest --cov --cov-report=xml tests/
      - name: 'Upload code coverage result'
        uses: actions/upload-artifact@v2
        with:
          name: coverage ${{ matrix.python-version }}
          path: coverage.xml
          retention-days: 1
      - name: Upload to Codecov
        uses: codecov/codecov-action@v2.0.2
