name: pytest

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - name: Get code
        uses: actions/checkout@v2
      - name: Python setup  ${{ matrix.python-version }}
        uses: actions/setup-python@v2.2.2    
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run tests
        run: pytest
        
        
